aliases:
  # Original command
  "gamemode creative":
    aliases:
      - "poggerpower"
      - "i am stupid"
    enabled: true
    matchPriority: NORMAL
    also:
      message:
        - "Ok you're going into creative time"
        - "Hi!!"
      playerCommand:
        - "me im going into creative mode guys"
      consoleCommand:
        - "say %name% is going into creative!"
      sendToServer: "creative"
    condition:
      permission:
        requiredPermission: "yamama"
        noPermissionMessage: "No permission, bitch"
      inWorld: "world"
  # Original command
  "rules":
    aliases:
      - "rules"
      - "i love rules"
    enabled: true
    matchPriority: NORMAL
    type: MESSAGE
    # ALSO or ONLY
    also:
      message:
        - "These are the rules:"
        - "be nice!"